---
- name: 'TASK 2: Configure Repository I'
  hosts: localhost
  tasks:
    - name: Mount iso
      mount:
        path: /ftp_repo
        src: /dev/sr0
        fstype: iso9660
        state: mounted
    - name: Install ftp
      dnf:
        name:
          - vsftpd
          - firewalld
        state: present
    - name: Configure Firewall
      firewalld:
        service: ftp
        permanent: yes
        state: enabled
        immediate: yes
    - name: Enable anon ftp
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable='
        insertafter: '^#anonymous_enable='
        line: anonymous_enable=YES
    - name: Configure anon root ftp
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anon_root='
        insertafter: '^#anon_root='
        line: anon_root=/ftp_repo
    - name: Enable ftp
      systemd:
        name: vsftpd
        state: restarted
        enabled: yes
    - name: Configure Selinux
      include_role:
        name: rhel-system-roles.selinux
      vars:
        selinux_booleans:
          - { name: 'ftpd_full_access', state: 'on', persistent: 'yes' }




     
