---
- name: 'TASK 3: Configure Repository II'
  hosts: localhost
  tasks:
    - name: Install apache and firewalld
      dnf:
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: present
    - name: Configure firewall
      with_items:
        - http
        - https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
    - name: Configure apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot "/var/www/html"'
        insertafter: '^#DocumentRoot "/var/www/html"'
        line: DocumentRoot "/http_repo"
    - name: Configure apache
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^<Directory "/var/www/html">'
        insertafter: '^#<Directory "/var/www/html">'
        line: <Directory "/http_repo">
    - name: Restart apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: Configure Selinux
      include_role:
        name: rhel-system-roles.selinux
      vars:
        selinux_fcontexts:
          - { target: '/http_repo(/.*)?', setype: 'httpd_sys_content_t', ftype: 'a', state: 'present' }
        selinux_restore_dirs:
          - /http_repo







