---
- name: File Content
  hosts: all
  become: true
  tasks:
    - name: Set MOTD on group proxy
      when:
        - "'proxy' in  hostvars[inventory_hostname]['group_names']"
      copy:
        dest: /etc/motd
        content: Welcome to HAProxy server
    - name: Set MOTD on group webserver
      when:
        - "'webserver' in  hostvars[inventory_hostname]['group_names']"
      copy:
        dest: /etc/motd
        content: Welcome to Apache server
    - name: Set MOTD on group database
      when:
        - "'database' in  hostvars[inventory_hostname]['group_names']"
      copy:
        dest: /etc/motd
        content: Welcome to MySQL server



