---
- name: 'TASK 6: File Content'
  hosts: all
  become: True
  tasks:
    - name: On proxy Group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['proxy']
      copy:
        content: Welcome to HAProxy server
        dest: /etc/motd
    - name: On webserver Group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      copy:
        content: Welcome to Apache server
        dest: /etc/motd
    - name: On database Group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      copy:
        content: Welcome to MySQL server
        dest: /etc/motd
