---
- name: 'TASK 6: File Content'
  hosts: all
  tasks:
    - name: On proxy hosts
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['proxy']
      copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd
    - name: On webserver hosts
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      copy:
        content: "Welcome to Apache server"
        dest: /etc/motd
    - name: On database hosts
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      copy:
        content: "Welcome to MySQL server"
        dest: /etc/motd
    - shell:
        cmd: cat /etc/motd
      register: motd
    - debug:
        msg: "{{ motd.stdout_lines }}"

