---
- name: 'TASK 6: File Content'
  hosts: all
  become: True
  tasks:
    - name: On group Proxy
      when:
        - "'proxy' in hostvars[inventory_hostname]['group_names']"
      copy:
        content: Welcome to HAProxy server
        dest: /etc/motd
    - name: On group Webserver
      when:
        - "'webserver' in hostvars[inventory_hostname]['group_names']"
      copy:
        content: Welcome to Apache server
        dest: /etc/motd
    - name: On group Database
      when:
        - "'database' in hostvars[inventory_hostname]['group_names']"
      copy:
        content: Welcome to MySQL server
        dest: /etc/motd
        
