---
- name: 'TASK 7: Configure SSH Server'
  hosts: all
  become: True
  tasks:
    - name: Disable XFor
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding '
        insertafter: '^#X11Forwarding '
        line: X11Forwarding no
    - name: Modify MaxAuthTries
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries '
        insertafter: '^#MaxAuthTries '
        line: MaxAuthTries 3
    - name: Restarted sshd
      systemd:
        name: sshd
        state: restarted
        enabled: yes
