---
- name: 'TASK 7: Configure SSH Server'
  hosts: all
  tasks:
    - name: Modify X11
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding '
        insertafter: '^#X11Forwarding '
        line: X11Forwarding no
      notify: restart-sshd
    - name: Modify MaxAuth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries '
        insertafter: '^#MaxAuthTries '
        line: MaxAuthTries 3
      notify: restart-sshd
  handlers:
    - name: restart-sshd
      systemd:
        name: sshd
        state: restarted
        enabled: yes
