---
- name: 'TASK 8: LVM I'
  hosts: all
  become: True
  tasks:
    - when:
        - "'vdb' in ansible_facts['devices']"
      block:
        - name: Create Partition
          parted:
            device: /dev/vdb
            number: 1
            state: present
        - name: Create VG
          lvg:
            vg: vgdata
            pvs: /dev/vdb1
            pesize: '8'
        - name: Create LV
          lvol:
            vg: vgdata
            lv: lvdata
            size: 100%VG
            state: present
        - name: Formatting
          filesystem:
            fstype: xfs
            dev: /dev/vgdata/lvdata
        - name: mount
          mount:
            path: /data
            src: /dev/vgdata/lvdata
            fstype: xfs
            state: mounted
