---
- name: 'TASK 8: LVM I'
  hosts: all
  tasks:
    - name: Only server has second drive
      when:
        - ansible_facts['devices']['vdb'] is defined
      block:
        - name: Partition disk
          parted:
            device: /dev/vdb
            number: 1
            state: present
        - name: Create VG
          lvg:
            vg: vgdata
            pvs: /dev/vdb1
            pesize: 8M
        - name: Create LV
          lvol:
            vg: vgdata
            lv: lvdata
            size: 100%VG
        - name: Create FS
          filesystem:
            fstype: xfs
            dev: /dev/vgdata/lvdata
        - name: Mount
          mount:
            path: /data
            src: /dev/vgdata/lvdata
            fstype: xfs
            state: mounted

  


      
