---
- name: 'TASK 8: LVM I'
  hosts: all
  become: True
  tasks:
    - name: On server that has second drive vdb
      when:
        - " 'vdb' in ansible_facts['devices']"
      block:
        - name: create partition in /dev/vdb
          parted:
            device: /dev/vdb
            number: 1
            state: present
        - name: Create VG vgdata
          lvg:
            vg: vgdata
            pvs: /dev/vdb1
            pesize: 8M
        - name: Create LV lvdata
          lvol:
            vg: vgdata
            lv: lvdata
            size: 100%FREE
        - name: Formatting lvdata with xfs
          filesystem:
            fstype: xfs
            dev: /dev/vgdata/lvdata
        - name: Mounting 
          mount:
            path: /data
            src: /dev/vgdata/lvdata
            fstype: xfs
            state: mounted
            
        
        
