---
- name: 'TASK 9: LVM II'
  hosts: all
  tasks:
    - name: vgdata not exists
      when:
        - ansible_facts['lvm']['vgs']['vgdata'] is not defined
      debug:
        msg: vgdata does not exists
    - name: vgdata exists
      when:
        - ansible_facts['lvm']['vgs']['vgdata'] is defined
      debug:
        msg: vgdata exists
    - name: vgdata exists
      when:
        - ansible_facts['lvm']['vgs']['vgdata'] is defined and
          ansible_facts['lvm']['vgs']['vgdata']['free_g'] < '1'
      debug:
        msg: Insufficient disk space available



