---
- name: 'TASK 9: LVM II'
  hosts: all
  become: True
  tasks:
    - name: If vgdata does not exists
      when:
        - "'vgdata' not in ansible_facts['lvm']['vgs']"
      debug:
        msg: vgdata does not exist
    - name: If vgdata exists
      when:
        - "'vgdata' in ansible_facts['lvm']['vgs']"
      debug:
        msg: vgdata exists
    - name: vgdata exist an has less than 1 GB
      when:
        - "'vgdata' in ansible_facts['lvm']['vgs']"
        - ansible_facts['lvm']['vgs']['vgdata']['size_g'] < '1'
      debug:
        msg: insufficient disk space available
