---
- name: 'TASK 9: LVM II'
  hosts: all
  become: True
  tasks:
    - name: vgdata exists
      when:
        - " 'vgdata' not in ansible_facts['lvm']['vgs']"
      debug:
        msg: vgdata does not exists
    - name: vgdata exists
      when:
        - "'vgdata' in ansible_facts['lvm']['vgs']"
      debug:
        msg: vgdata does exists
    - name: vgdata .es 1GB
      when:
        - "'vgdata' in ansible_facts['lvm']['vgs']"
      block:
        - when:
            - ansible_facts['lvm']['vgs']['vgdata']['free_g'] < '1'
          debug:
            msg: Insufficient disk space available”



