---
- name: 'TASK 10: Users and Groups I'
  hosts: all
  vars_files:
    - ./vars/10-user-list.yml
    - ./vars/10-secret.yml
  tasks:
    - name: Users ID starts with 1
      with_items: "{{ users }}"
      when:
        - item.uid | string | first == '1'
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      user:
        name: "{{ item.username }}"
        append: yes
        groups: wheel
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"

