---
- name: 'TASK 10: Users and Groups I'
  hosts: all
  vars_files:
    - ./vars/10-user-list.yml
    - ./vars/10-secret.yml
  tasks:
    - name: Users ID start with 1
      with_items: "{{ users }}"
      when:
        - item.uid | string | first == '1' and
          hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      user:
        name: "{{ item.username }}"
        groups: wheel
        shell: /bin/bash
        append: yes
        password: "{{ user_password | password_hash ('sha512') }}"
    - name: Users ID start with 2
      with_items: "{{ users }}"
      when:
        - item.uid | string | first == '2' and
          hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      user:
        name: "{{ item.username }}"
        groups: wheel
        shell: /bin/bash
        append: yes
        password: "{{ user_password | password_hash ('sha512') }}"




