---
- name: 'TASK 10: Users and Groups I'
  hosts: all
  become: True
  vars_files:
    - ./vars/10-user_list.yml
    - ./vars/10-secret.yml
  tasks:
    - name: Users ID start with 1
      with_items: "{{ users }}"
      when:
        - ("'webserver' in hostvars[inventory_hostname]['group_names']") and
          (item.uid | string | first == '1')
      user:
        name: "{{ item.username }}"
        groups: wheel
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"

    - name: Users ID start with 2
      with_items: "{{ users }}"
      when:
        - "'database' in hostvars[inventory_hostname]['group_names']"
        - item.uid | string | first == '2'
      user:
        name: "{{ item.username }}"
        groups: wheel
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
