---
- name: 'TASK 11: Users and groups II'
  hosts: all
  vars_files:
    - ./vars/11-user_list2.yml
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      block:
        - group:
            name: "{{ item.department }}"
            state: present
          with_items: "{{ users }}"
          when:
            - item.department == 'profs'
        - user:
            name: "{{ item.name }}"
            groups: "{{ item.department }}"
            password: "{{ item.password | password_hash('sha256') }}"
          with_items: "{{ users }}"
          when:
            - item.department == 'profs'



