---
- name: 'TASK 11: Users and groups II'
  hosts: all
  vars_files:
    - ./vars/11-user_list2.yml
  tasks:
    - name: On webserver group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      block:
        - with_items: "{{ users }}"
          when:
            - item.department == 'profs'
          group:
            name: "{{ item.department }}"
        - with_items: "{{ users }}"
          when:
            - item.department == 'profs'
          user:
            name: "{{ item.name }}"
            password: "{{ item.password | password_hash ('sha256') }}"
            groups: "{{ item.department }}"







