---
- name: 'TASK 11:  Users and groups II'
  hosts: all
  become: True
  vars_files:
    - ./vars/11-user_list2.yml
  tasks:
    - name: On webserver
      when:
        - "'webserver' in hostvars[inventory_hostname]['group_names']"
        - item.department == 'profs' 
      block:
        - with_items: "{{ users }}"
          group:
            name: "{{ item.department }}"
            state: present
        - with_items: "{{ users }}"
          user:
            name: "{{ item.name }}"
            groups: "{{ item.department }}"
            password: "{{ item.password | password_hash('sha256') }}"


