---
- name: 'TASK 12: Scheduled Tasks'
  hosts: all
  tasks:
    - name: On proxy group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['proxy']
      cron:
        name: time.log
        job: date >> /var/log/time.log
        user: root
        minute: '0'
