---
- name: 'TASK 12: Scheduled Tasks'
  hosts: all
  tasks:
    - name: Cron
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['proxy']
      cron:
        name: "time.log"
        minute: "0"
        job: "date >> /var/log/time.log"
        user: root
