---
- name: Software Repositories
  hosts: all
  become: True
  tasks:
    - when:
        - "'database' in hostvars[inventory_hostname]['group_names']"
      block:
        - name: MySQL 8 Repo
          yum_repository:
            name: mysql56-community
            description: MySQL 8 YUM Repo
            file: mysql8-community
            baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/7/x86_64/
            gpgcheck: yes
            gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
            enabled: yes
        - shell:
            cmd: dnf repolist
          register: repolist
        - debug:
            var: repolist['stdout_lines']
