---
- name: 'TASK15: Create and Work with Roles II'
  hosts: all
  tasks:
    - name: Apache rol
      when: 
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      include_role:
        name: 15-sample-apache
