---
- name: 'TASK 16: Download Roles From Ansible Galaxy and Use Them'
  hosts: all
  become: True
  vars:
    haproxy_frontend_name: 'hafrontend'
    haproxy_frontend_bind_address: '*'
    haproxy_frontend_port: 80
    haproxy_frontend_mode: 'http'
    haproxy_backend_name: 'habackend'
    haproxy_backend_mode: 'http'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_servers:
      - name: node2.example.com
        address: 192.168.122.102:80
      - name: node3.example.com
        address: 192.168.122.103:80
    services:
      - http
      - https
  tasks:
    - when:
        - "'proxy' in hostvars[inventory_hostname]['group_names']"
      block:
        - include_role:
            name: geerlingguy.haproxy
        - with_items: "{{ services }}"
          firewalld:
            service: "{{ item }}"
            permanent: yes
            state: enabled
            immediate: yes
  
