---
- name: 'TASK 17: Security'
  hosts: all
  vars:
    selinux_booleans:
      - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      include_role:
        name: linux-system-roles.selinux


