---
- name: 'TASK 18: Use Conditionals to Control Play Execution'
  hosts: all
  tasks:
    - name: More than 1500MB of RAM
      when:
        - ansible_facts['memtotal_mb'] > 1500
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
    - name: Less than 1500MB of RAM
      when:
        - ansible_facts['memtotal_mb'] <= 1500
      debug:
        msg: Server memory less than 1500 MB
