---
- name: 'TASK 19: Use Archiving'
  hosts: all
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      block:
        - name: Create file
          copy:
            content: 'dev,test,qa,prod.'
            dest: /mysql_backups/database_list.txt
        - name: Create tar
          archive:
            path: /mysql_backups/database_list.txt
            dest: /mysql_backups/archive.gz
            format: gz
