---
- name: 'TASK 20: Work with Ansible Facts'
  hosts: all
  become: True
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      block:
        - name: Create dir
          file:
            path: /etc/ansible/facts.d
            state: directory
        - name: Create fact
          copy:
            content: "[sample_exam]\nserver_role=mysql"
            dest: /etc/ansible/facts.d/custom.fact


