---
- name: 'TASK 20: Work with Ansible Facts'
  hosts: all
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      block:
        - file:
            dest: /etc/ansible/facts.d
            state: directory
        - copy:
            content: "[sample_exam]\nserver_role=mysql\n"
            dest: /etc/ansible/facts.d/custom.fact
