---
- name: 'TASK 20: Work with Ansible Facts'
  hosts: all
  become: True
  tasks:
    - name: Create custom facts
      when:
        - "'database' in hostvars[inventory_hostname]['group_names']"
      block:
        - file:
            dest: /etc/ansible/facts.d
            state: directory
        - copy:
            dest: /etc/ansible/facts.d/custom.fact
            content: "[sample_exam]\nserver_role=mysql"
        - debug:
            msg: "{{ ansible_local.custom.sample_exam }}"

