---
- name:
  hosts: all
  become: True
  tasks:
    - when: "'database' in hostvars[inventory_hostname]['group_names']"
      block:
        - shell: mkdir -p /etc/ansible/facts.d
        - copy:
            content: "[sample_exam]\nserver_role = mysql"
            dest: /etc/ansible/facts.d/custom.fact
        - debug:
            #msg: "{{ ansible_machine }}"
            #msg: "{{ ansible_facts['machine'] }}"
            msg: "{{ ansible_local.custom.sample_exam }}"
            #msg:  "{{ ansible_facts['local']['custom'] }}"
