---
- name: 'TASK 21: Create and Use Templates to Create Customized Configuration Files'
  hosts: all
  become: True
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      template:
        src: ./templates/server_list.j2
        dest: /etc/server_list.txt
        mode: 0600
        setype: net_conf_t
