---
- name: 'TASK 22: Facts'
  hosts: all
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto
    - file:
        dest: /root/packages.txt
        state: touch
    - name: Get Info
      with_items:
        - kernel
        - bash
        - glibc
      lineinfile:
        line: "{{ ansible_facts.packages[item][0]['name'] }} = {{ ansible_facts.packages[item][0]['version'] }}"
        dest: /root/packages.txt
