---
- name: Facts
  hosts: all
  become: True
  vars:
    packages:
      - kernel
      - bash
      - glibc
  tasks:
    - name: Gather the rpm package facts
      block:
        - package_facts:
           manager: auto
        - file:
            dest: /root/packages.txt
            state: touch
        - name: Check whether a package called {{ item }} is installed
          with_items: "{{ packages }}"
          when: 
            - item in ansible_facts.packages
          lineinfile:
            path: /root/packages.txt
            line: "{{ item }} = {{ ansible_facts.packages[item][0]['version']  }}"

