---
- name: 'TASK 22:  Facts'
  hosts: all
  become: True
  vars:
    packages:
      - kernel
      - bash
      - glibc
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto 
    - name: Genereta report
      with_items: "{{ packages }}"
      # debug:
      #  msg: "{{ ansible_facts['packages'][item][0]['name'] }}"
      lineinfile:
        line: "{{ ansible_facts['packages'][item][0]['name'] }} = {{ ansible_facts['packages'][item][0]['version'] }}"
        path: /root/packages.txt

