---
- name: 'TASK 23: VAULT'
  hosts: all
  become: True
  vars_files:
    - ./23-cloudpass
  tasks:
    - name: Create file
      file:
        dest: /root/cloudcreds.txt
        state: touch
    - name: Create content
      copy:
        content: "CLOUDID = {{ CLOUDID }}\nCLOUDPASS = {{ CLOUDPASS }}"
        dest: /root/cloudcreds.txt
