---
- name: 'TASK 23: VAULT'
  hosts: all
  become: True
  vars_files:
    - ./23-cloudpass
  tasks:
    - name: Create file
      file:
        dest: /root/cloudcreds.txt
        state: touch
    - name: Create file
      with_items: "{{ variables }}"
      lineinfile:
        line: "{{ item.varname }} = {{ item.value }}"
        path: /root/cloudcreds.txt

  
