---
- name: 'TASK 25: Manage of dnf group'
  hosts: all
  tasks:
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver'] or
          hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      dnf:
        name:
          - perl
          - php
        state: present
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['database']
      dnf:
        name: '@Development tools'
        state: present
    - when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      dnf:
        name: '*'
        state: latest
