---
- name: 'TASK 25: Manage of dnf group'
  hosts: all
  become: True
  tasks:
    - name: Install Group
      when:
        - hostvars[inventory_hostname]['inventory_hostname'] in hostvars[inventory_hostname]['groups']['webserver']
      dnf:
        name: '@Development tools'
        state: present 
