---
# tasks file for 15-sample-apache
- name: Only in webserver group
  when:
    - "'webserver' in hostvars[inventory_hostname]['group_names']"
  block:
    - name: Install Apache packages
      dnf:
        name:
          - httpd
          - mod_ssl
          - php
        state: present
    - name: Configure firewalld
      with_items: "{{ services }}"
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
    - name: Configuring index
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      notify: restart_httpd
      


