---
# tasks file for 15-sample-apache
- dnf:
    name:
      - httpd
      - mod_ssl
    state: present
- systemd:
    name: httpd
    state: restarted
    enabled: yes
- with_items:
    - http
    - https
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
- template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart-httpd

