---
# tasks file for 15-sample-apache
- name: Install apache
  dnf:
    name:
      - httpd
      - mod_ssl
    state: present
- name: Firewall
  with_items:
    - http
    - https
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
- name: Enable httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes
- name: Configure index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart-httpd
